name: Flutter 基础知识学习
type: flutter
steps:
  - name: 函数接受给定Widiget，并且使其成为小部件树的根
    directory: step_01
    has_solution: true
  - name: Using Material Components 使用Material组件构建
    directory: step_02
    has_solution: true
  - name: Build the child according to its activation state
    directory: step_03
    has_solution: true
  - name: Activate the child when the new index match its position
    directory: step_04
    has_solution: true
  - name: Control children updates more precisely
    directory: step_05
    has_solution: false
  - name: Completion
    directory: completion
    has_solution: false
